fix: add prettyprint to any code tag
googleapis/doc-pipeline pull request #151
Opened 2021-11-12 15:37 UTC by fhinkel

translate and directory get added later in the pipeline. Thus adding prettyprint
to any code tage that doesn't specify a language.

2021-11-12 15:51 UTC, jskeet reviewed
I'm sufficiently unsure about this that I'd prefer to defer to Tyler, I'm afraid.

2021-11-12 16:10 UTC, fhinkel commented
Yeah, I think this is not the way to go. 
The example code for Node.js looks like this after `docfx` created the HTML and I don't know how to add `prettyprint` to just those: 
```
<pre><code>const {Storage} = require('@google-cloud/storage');                                                                                                                                                                   
  const storage = new Storage();                                                                                                                                                                                                           
</code></pre>
```

2021-11-12 16:47 UTC, tbpg requested changes
Yeah, I don't think we want to do this as-is. See https://github.com/googleapis/doc-templates/pull/273. We have `prettyprint` on all `pre` elements in the template:

```
$ grep -R '<pre' .
./partials/class.tmpl.partial:  <pre class="prettyprint{{#wrapdeclarationcode}} wrap-code{{/wrapdeclarationcode}}"><code>{{syntax.content.0.value}}</code></pre>
./partials/class.header.tmpl.partial:  <pre class="prettyprint{{#wrapdeclarationcode}} wrap-code{{/wrapdeclarationcode}}"><code>{{syntax.content.0.value}}</code></pre>
./partials/uref/class.tmpl.partial:  <pre class="prettyprint{{#wrapdeclarationcode}} wrap-code{{/wrapdeclarationcode}}"><code>{{syntax.content.0.value}}</code></pre>
./partials/uref/class.tmpl.partial:    <pre class="prettyprint"><code>{{content}}</code></pre>
./partials/uref/namespace.tmpl.partial:        <pre class="prettyprint{{#wrapdeclarationcode}} wrap-code{{/wrapdeclarationcode}}"><code>{{{syntax.content.0.value}}}</code></pre>
./partials/uref/namespace.tmpl.partial:            <pre class="prettyprint{{#wrapdeclarationcode}} wrap-code{{/wrapdeclarationcode}}"><code>{{{syntax.content.0.value}}}</code></pre>	
./partials/uref/namespace.examples.tmpl.partial:<pre class="prettyprint"><code>{{content}}</code></pre>
```

So, it seems fine to add `prettyprint` to all input `pre` elements?

2021-11-12 16:57 UTC, fhinkel commented
>  We have `prettyprint` on all `pre` elements in the template:

I'm not sure what that means. The rendered Node.js examples don't have them. I feel like the template doesn't correctly get applied to them which is why I'm trying to add in doc-pipeline. This is how my code tags lock in prod: 

```
<devsite-code no-copy="" data-copy-event-label="">
  <div class="devsite-code-buttons-container" role="group" aria-label="Action buttons">
    <button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="Dark code theme" data-title="Dark code theme">
    </button>
    <button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="Light code theme" data-title="Light code theme">
    </button>
  </div>
  <pre translate="no" dir="ltr" is-upgraded="">
    <code translate="no" dir="ltr">
        const {Storage} = require('@google-cloud/storage');
        const storage = new Storage();
    </code>
  </pre>
</devsite-code>
```

2021-11-12 17:12 UTC, tbpg commented
Options for inserting code blocks:

1. The YAML says "here is some code, hey template, will you put it in a `<pre><code>` for me?"
2. The YAML says "here is MarkDown, hey DocFX will you turn it into HTML?"
3. The YAML says "here is HTML, don't change it at all."
    * Note: I assumed HTML would be unchanged, but depending on the field it will still be interpreted as MarkDown... See b/201714446.

Looks like Node.js is using the second option. The DocFX MarkDown processor doesn't use the template -- it just converts to HTML. Once that field is converted to HTML, the template says where to put the generated HTML in the output.

The `grep` above is for option 1 -- everywhere the template says how to insert the code block includes `prettyprint`.

2021-11-12 17:18 UTC, fhinkel commented
Yes, it's markdown. If the templates aren't used, then where's the right place to add the class?

2021-11-12 17:23 UTC, tbpg commented
Two options I see:

1. In the Node.js `cloud-rad` package. Convert the fenced code blocks into `<pre class="prettyprint"><code>...`.
2. In `doc-pipeline`, like this PR, except move the `prettyprint` to the `pre` instead of the `code`.

2021-11-12 17:40 UTC, fhinkel commented
How does this look? 
```
html = html.replace(  # Add prettyprint to Nodejs examples
            "<pre><code>".encode(), '<pre class="prettyprint"><code>'.encode()
        )
```

Do we potentially break anything by adding this class for all languages? We're already doing pre-processing in cloud-rad, might fit better to add it there.

2021-11-12 19:27 UTC, tbpg commented
> Do we potentially break anything by adding this class for all languages? We're already doing pre-processing in cloud-rad, might fit better to add it there.

I don't think so? The worst case is pretty printing a `pre` when it shouldn't be, which isn't too bad. But, if we ever find somewhere where we don't want `prettyprint`, it seems like it would be hard to undo? If it's not hard to do the processing in `cloud-rad`, I'd do that. But, if it's difficult, I'm willing to risk it here if you are.

Another idea is to do it here but restrict this replacement to only Node.js? Best of both worlds?

2021-11-13 01:53 UTC, fhinkel commented
OK, let me try in cloud-rad first. Since the other languages don't need it, no point in centralizing it here.

2021-11-13 01:53 UTC, closed without merging