test: update test to allow run in parallel
googleapis/doc-pipeline pull request #643
Opened 2024-05-05 07:40 UTC by dandhlee

Updating unit test to be able to run in parallel.

Previously, we simply checked that more blobs are created and deleted old ones - however, this caused a lot of issues when multiple presubmits are run at the same time.

Instead, changed to create fixed blobs (using metadata notion to work with multi-version and semver) and check for those specific blobs.

For xref blobs I've decided to try to keep them there, since `generate.get_xref` takes the entire bucket, adding unique identifiers for these blobs really doesn't make sense, and the point of the xref blobs is to test its content not to test that they get uploaded to the bucket, at least in this point.

Verified that the tests run by running several tests altogether with #645.

Fixes #368.

2024-05-06 12:14 UTC, tbpg requested changes

2024-05-06 12:14 UTC, tbpg commented on tests/test_generate.py
> +# Unique identifier for runnig parallel tests.
```suggestion
# Unique identifier for running tests in parallel.
```

2024-05-06 12:14 UTC, tbpg commented on tests/test_generate.py
> +    blobs = list(storage_client.list_blobs(test_bucket))
This could wipe out any other blobs that are in the bucket. We should filter to just the blobs the test cares about (that are a day old).

2024-05-06 12:14 UTC, tbpg commented on tests/test_generate.py
>      # Expect 2 more files: an output blob and an output xref file.
Update comment.

2024-05-06 12:14 UTC, tbpg commented on tests/test_generate.py
> +    _add_uuid_to_metadata(yaml_dir, new_metadata)
It feels like we should do this in `api_dir`, next to where `docs.metadata` gets updated.

2024-05-06 12:14 UTC, tbpg commented on tests/test_generate.py
> +def cleanup_bucket(storage_client, test_bucket):
Nit (verb instead of adjective):
```suggestion
def clean_up_bucket(storage_client, test_bucket):
```

2024-05-06 21:57 UTC, dandhlee reviewed
Thank you for the review! Please take a look again.

2024-05-08 17:13 UTC, tbpg approved these changes

2024-05-09 21:02 UTC, dandhlee commented on tests/test_generate.py
> +    text_format.Merge(metadata_path.read_text(), metadata)
Somehow Kokoro doesn't seem to be recognizing this... I'll debug for this later.

2024-05-09 23:17 UTC, merged